version: '3.7'

services:
  sim:
    tty: true
    build: ./px4

  bridge:
    build:
      context: ../
      dockerfile: test/mavp2p/Dockerfile
    read_only: yes
    command: >
      --hb-systemid=135
      udps:0.0.0.0:14550
      udps:0.0.0.0:5600
    ports:
    - '5600:5600/udp'
