name: nightly_binaries

on:
  workflow_dispatch:

jobs:
  nightly_binaries:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - run: make binaries

    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: binaries
